#!/bin/bash

### BEGIN INIT INFO
# Provides:          control-panel
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: your description here
### END INIT INFO

export SPRING_CONFIG_LOCATION=classpath:/application.properties,file:/etc/control-panel/application.properties
java -jar /opt/control-panel/control-panel.jar
